Merged https://github.com/franciscojunior/Npgsql2/pull/6 from roji.
Pull origin: https://github.com/roji/Npgsql2.git branch xbuild

Original commit message:

Added Mono-Debug and Mono-Release msbuild configuration for use with xbuild

Appears to build just fine! I also tried to muck around with MonoDevelop but it has some trouble with the EmbeddedResources, will try to take a look (less important). This could be a first step for getting rid of both the NAnt and the mdp/mds...

Note that the unit test project doesn't build on Windows, seems like these need to be cleaned up
: error CS2001: Source file xmlModel/XmlTest.ObjectLayer.cs' could not be found
: error CS2001: Source filexmlModel/XmlTest.Views.cs' could not be found